In [16]:
import numpy as np

damped_coef = 0.85
epoch = 100

In [17]:
M = np.random.randn(3, 3)
print M
PR = np.random.randn(3, 1)
print PR

[[ 0.22770988  0.84431371  0.82372737]
 [-0.94689299 -0.25825932  2.27854087]
 [ 0.05227562  0.98508561  0.33249366]]
[[ 1.12049565]
 [-0.0881624 ]
 [-0.77158106]]


In [15]:
np.dot(M, PR)

array([[-1.49482697],
       [ 0.06531309],
       [-0.31393641]])

In [18]:
for i in xrange(epoch):
    PR = (1 - damped_coef) + damped_coef*np.dot(M, PR)
    print i
    print PR

0
[[-0.23663205]
 [-2.22685473]
 [-0.09209591]]
1
[[-1.55842295]
 [ 0.65092788]
 [-1.75113886]]
2
[[-0.91058069]
 [-2.13011639]
 [ 0.13088315]]
3
[[-1.46331925]
 [ 1.60398237]
 [-1.6370658 ]]
4
[[-0.12832728]
 [-2.19494428]
 [ 0.96536253]]
5
[[-0.77416028]
 [ 2.60479574]
 [-1.42074857]]
6
[[ 0.87477062]
 [-2.55036457]
 [ 1.89512412]]
7
[[-0.184091  ]
 [ 3.67619015]
 [-1.41100928]]
8
[[ 1.76470371]
 [-3.24161747]
 [ 2.82119887]]
9
[[ 0.14047758]
 [ 4.90524787]
 [-1.68854065]]
10
[[ 2.51526014]
 [-4.31016427]
 [ 3.78630305]]
11
[[ 0.19462523]
 [ 6.40489849]
 [-2.27715143]]
12
[[ 3.18986326]
 [-5.82294708]
 [ 4.87804772]]
13
[[  3.92816614e-03]
 [  8.30847192e+00]
 [ -3.20531496e+00]]
14
[[ 3.86921371]
 [-7.88496582]
 [ 6.20116239]]
15
[[ -0.41802042]
 [ 10.77690101]
 [ -4.5277656 ]]
16
[[  4.63311538]
 [-10.64849644]
 [  7.87553481]]
17
[[ -1.08111598]
 [ 14.01157632]
 [ -6.33457881]]
18
[[  5.5611163 ]
 [-14.32423833]
 [ 10.04389707]]
19
[[ -2.02123718]
 [ 18.27116351]
 [ -8.75830444]]
